// config/constants.ts

// Canonical list of skills (source of truth)
export const SKILLS = [
  // --- Existing web/dev skills ---
  "Next.js",
  "React",
  "GraphQL",
  "Nest.js",
  "express.js",
  "Node.js",
  "MongoDB",
  "Typescript",
  "Javascript",
  "HTML 5",
  "CSS 3",
  "React Native",
  "Angular",
  "Redux",
  "Socket.io",
  "Material UI",
  "Tailwind CSS",
  "AWS",
  "Bootstrap",
  "Google Auth",
  "MySQL",
  "Java",
  "Databricks",
  "Python",
  "Docker",
  "Kubernetes",
  "PostgreSQL",
  "Redis",
  "Git",
  "CI/CD",
  "Jenkins",
  "FastAPI",
  "Django",
  "Vue.js",
  "Sass",
  "Firebase",
  "Azure",
  "Google Cloud",
  "Figma",
  "Webpack",
  "Jest",
  "Cypress",
  "Storybook",
  "Prisma",
  "Supabase",
  "Vercel",
  "Netlify",
  "Three.js",
  "WebGL",
  "TensorFlow",
  "PyTorch",
  "Spring Boot",
  "Laravel",
  "PHP",
  "Flutter",
  "Dart",
  "Flask",
  "SQL",
  "NoSQL",
  "Framer Motion",

  // --- Added mech / data / CAD / CAE skills ---
  "R",
  "MATLAB",
  "SolidWorks",
  "Siemens NX",
  "Creo",
  "Onshape",
  "Fusion 360",
  "Rhino",
  "Grasshopper",
  "ANSYS FEA",
  "Motion Capture",
  "JMP",
  "Data Synthesis",
] as const;

export type ValidSkills = (typeof SKILLS)[number];

// (Leave your ValidCategory / ValidExpType / ValidPages as-is)
